highlighter: pygments
permalink: /news/:title
sass:
    style: :compressed
    sass_dir: styles/_snippets
collections:
- sections
- organizers
- participants
defaults:
    -
        scope:
            path: "_posts"
        values:
            layout: "news"
navigation:
  - title : "Home"
    url   : "/"
